server:
  port: 8997

spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:mysql://localhost:3307/emotions?useSSL=false
    username: user
    password: emailsemotions
    initialization-mode: ALWAYS
info:
  app:
    uuid: ${app_uuid}
  tags:
    name: ${spring.application.name}
    app-id: ${info.app.uuid}
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${info.app.uuid}
    # Lease Reneval and Expiration times - to unregister in eureka
    leaseRenewalIntervalInSeconds: 15
    leaseExpirationDurationInSeconds: 30
    health-check-url-path: /actuator/health
  client:
    healthcheck:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    schema: classpath*:db/mysql/schema.sql
    data: classpath*:db/mysql/data.sql
    url: jdbc:mysql://localhost:3307/emotions?useSSL=false
    username: user
    password: emailsemotions
    initialization-mode: ALWAYS
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://db-emotions:3306/emotions?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: user
    password: emailsemotions
    initialization-mode: ALWAYS
#   zipkin:
#     baseUrl: http://tracing-server:9411
info:
  app:
    uuid: ${app_uuid}
  tags:
    name: ${spring.application.name}
    app-id: ${info.app.uuid}

eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${info.app.uuid}
    # Lease Reneval and Expiration times - to unregister in eureka
    leaseRenewalIntervalInSeconds: 15
    leaseExpirationDurationInSeconds: 30
    health-check-url-path: /actuator/health
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
